Module spp audit log
OpenSPP/openspp-base pull request #32
Opened 2023-10-23 09:05 UTC by reichie020212

2023-11-09 05:14 UTC, kneckinator requested changes
Can you please add tests to the new modules @reichie020212 ?
Thanks!

2023-11-20 10:10 UTC, nhatnm0612 commented on spp_audit_log/models/spp_audit_rule.py
> +        while parent_rule_id:
@reichie020212 I think this logic will be improved if we are using searching domain operator `parent_of` or `child_of`

2023-12-06 04:23 UTC, reichie020212 commented
> Can you please add tests to the new modules @reichie020212 ? Thanks!

done adding tests

2023-12-08 00:32 UTC, gonzalesedwin1123 commented
Merged for transfer to mono-repo.

2023-12-08 00:32 UTC, merged