create base module to install minimum openspp module
OpenSPP/openspp-base pull request #9
Opened 2023-07-05 03:27 UTC by emjay0921

2023-07-06 01:07 UTC, gonzalesedwin1123 commented
@emjay0921 add the OpenG2P modules

2023-07-10 01:36 UTC, nhatnm0612 approved these changes

2023-07-10 02:54 UTC, reichie020212 approved these changes

2023-09-05 09:48 UTC, gonzalesedwin1123 requested changes
Please fix the pre-commit and automated tests errors

2023-09-05 10:19 UTC, gonzalesedwin1123 approved these changes

2023-09-05 10:20 UTC, gonzalesedwin1123 commented
@reichie020212 please fix the pre-commit and automated test errors

2023-09-07 08:17 UTC, merged